name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t telecom-churn-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 --name churn-container telecom-churn-app
        sleep 10

    - name: Check Docker container status
      run: docker ps -a 

    - name: Check Docker container logs
      run: docker logs churn-container 

    - name: Test Streamlit App
      run: curl http://localhost:8501

    - name: Stop container
      run: docker stop churn-container && docker rm churn-container
